/**
 * @fileoverview Constantes AEAT Modelo 184 — ejercicio 2025+.
 */

export const RECORD_LENGTH = 500;
export const MODELO = '184';

/** Valores alineados con la declaración real APARTAMENTOS GRACIA 4, C.B. */
export const MODELO_184_FISCAL = {
  clave: 'C' as const,
  subclave: '01' as const,
  tipoEntidad: 2,
  actividadPrincipal: 3,
  situacionInmuebleEspanaConCatastro: 1 as const,
  naturalezaInmuebleUrbano: 1 as const,
  claveTitularidad: 'T' as const,
  tipoParticipeResidente: 1 as const,
  tipoSoporteTelematico: 'T',
};

/** Código provincial INE (extracto; ampliar según necesidad). */
export const PROVINCE_NAME_TO_CODE: Record<string, string> = {
  ALAVA: '01',
  'ARABA/ÁLAVA': '01',
  ALBACETE: '02',
  ALICANTE: '03',
  ALMERIA: '04',
  AVILA: '05',
  BADAJOZ: '06',
  'ILLES BALEARES': '07',
  BALEARES: '07',
  BARCELONA: '08',
  BURGOS: '09',
  CACERES: '10',
  CADIZ: '11',
  CASTELLON: '12',
  'CIUDAD REAL': '13',
  CORDOBA: '14',
  'A CORUÑA': '15',
  'LA CORUÑA': '15',
  CUENCA: '16',
  GIRONA: '17',
  GERONA: '17',
  GRANADA: '18',
  GUADALAJARA: '19',
  GIPUZKOA: '20',
  GUIPUZCOA: '20',
  HUELVA: '21',
  HUESCA: '22',
  JAEN: '23',
  LEON: '24',
  LLEIDA: '25',
  LUGO: '27',
  MADRID: '28',
  MALAGA: '29',
  MURCIA: '30',
  NAVARRA: '31',
  OURENSE: '32',
  ASTURIAS: '33',
  PALENCIA: '34',
  'LAS PALMAS': '35',
  PONTEVEDRA: '36',
  SALAMANCA: '37',
  'SANTA CRUZ DE TENERIFE': '38',
  CANTABRIA: '39',
  SEGOVIA: '40',
  SEVILLA: '41',
  SORIA: '42',
  TARRAGONA: '43',
  TERUEL: '44',
  TOLEDO: '45',
  VALENCIA: '46',
  VALLADOLID: '47',
  VIZCAYA: '48',
  BIZKAIA: '48',
  ZAMORA: '49',
  ZARAGOZA: '50',
  CEUTA: '51',
  MELILLA: '52',
  'LA RIOJA': '26',
  GIRONA_ALT: '17',
};
